version: "3.8"

services:
  test:
    image: springcloud/spring-cloud-contract:2.2.1.RELEASE
    environment:
      - PUBLISH_ARTIFACTS=false
      - APPLICATION_BASE_URL=http://service:8088/
      - PROJECT_GROUP=com.demo
      - PROJECT_VERSION=0.0.1-SNAPSHOT
      - PROJECT_NAME=custom-contracts
    volumes:
      - "./contracts/:/contracts:ro"
      - "./build/spring-cloud-contract-output/:/spring-cloud-contract-output/"
  service:
    image: node:12
    command: bash -c "npm install -g mountebank && mb --configfile mountbank.json"
    ports:
      - "2525:2525"
    volumes: 
      - "./mountbank.json:/mountbank.json"